# Generated by Django 5.2.6 on 2025-09-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vschool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
